name: Frontend ESLint

on:
  push:
    paths:
      - 'frontend/system-info-dashboard/**'
  pull_request:
    paths:
      - 'frontend/system-info-dashboard/**'

jobs:
  lint:
    name: Lint Mobile App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/system-info-dashboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/system-info-dashboard/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint 