name: Composite Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Install IoT dependencies
        run: npm ci
        working-directory: pc-monitor-iot

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend/system-info-dashboard

      - name: Lint backend (syntax)
        run: npm test
        working-directory: backend

      - name: Run IoT tests
        run: npm test
        working-directory: pc-monitor-iot

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: frontend/system-info-dashboard 